// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using yemekoneri.Context;

namespace yemekoneri.Migrations
{
    [DbContext(typeof(YemekOneriDbContext))]
    [Migration("20200628154834_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("yemekoneri.Entities.Begen", b =>
                {
                    b.Property<int>("BegenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsLike")
                        .HasColumnType("bit");

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<int?>("YemekId")
                        .HasColumnType("int");

                    b.HasKey("BegenId");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("YemekId");

                    b.ToTable("Begens");
                });

            modelBuilder.Entity("yemekoneri.Entities.Kullanici", b =>
                {
                    b.Property<int>("KullaniciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SurName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KullaniciId");

                    b.ToTable("Kullanicis");
                });

            modelBuilder.Entity("yemekoneri.Entities.Yemek", b =>
                {
                    b.Property<int>("YemekId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("YemekAciklamasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YemekAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yorumlar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("YemekId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Yemeks");
                });

            modelBuilder.Entity("yemekoneri.Entities.Yorum", b =>
                {
                    b.Property<int>("YorumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<int?>("YemekId")
                        .HasColumnType("int");

                    b.Property<string>("YorumAciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YorumMail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("YorumId");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("YemekId");

                    b.ToTable("Yorums");
                });

            modelBuilder.Entity("yemekoneri.Entities.Begen", b =>
                {
                    b.HasOne("yemekoneri.Entities.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId");

                    b.HasOne("yemekoneri.Entities.Yemek", "Yemek")
                        .WithMany()
                        .HasForeignKey("YemekId");
                });

            modelBuilder.Entity("yemekoneri.Entities.Yemek", b =>
                {
                    b.HasOne("yemekoneri.Entities.Kullanici", "Kullanici")
                        .WithMany("Yemekler")
                        .HasForeignKey("KullaniciId");
                });

            modelBuilder.Entity("yemekoneri.Entities.Yorum", b =>
                {
                    b.HasOne("yemekoneri.Entities.Kullanici", "Kullanici")
                        .WithMany("Yorumlar")
                        .HasForeignKey("KullaniciId");

                    b.HasOne("yemekoneri.Entities.Yemek", "Yemek")
                        .WithMany()
                        .HasForeignKey("YemekId");
                });
#pragma warning restore 612, 618
        }
    }
}
